### ISSUE TITLE
Format Excel Node - message = "Success!"

### ISSUE THREAD

**Issue by teghill** [ksobon/Bumblebee#10]
Konrad,

The Format Excel node provides a Success! message when there has been no success. This can occur if the excel sheet is open or there is missing data or incorrect data being entered into it. I am not sure if this is a fix in this node or would require a fix other nodes such as Text Style, that do not contain a message if they are missing data inputs.

tim

ps thank you for all your hard work in developing Bumblebee and other nodes for Dynamo.

**Comment by ksobon** [comment]
OK, let me answer the missing error message from Text Style node if there are missing inputs. I don't provide a message because that node, basically doesn't need any inputs to work. I made it that way to allow users to specify all of the text style properties or none at all. If there is a missing input on a node, Dynamo provides an input by color coding it: 

![image](https://cloud.githubusercontent.com/assets/529781/12522610/a120be76-c11f-11e5-82a3-2e4e71632e2f.png)

Notice light grey color of the node that is missing an input. 

![image](https://cloud.githubusercontent.com/assets/529781/12522634/bc0b7ce4-c11f-11e5-8ead-bf4696c3e302.png)

Notice Dark Grey color of the node that has all inputs satisfied. 

This should be enough of a "tell" in my eyes and i didn't provide additional messages for that.

**Comment by teghill** [comment]
Konrad,

I didnt know the light grey vs dark grey thing. Thank you for pointing it out. I am afraid newbies like me are too busy looking at our cards to look for "tells". I will start to pay more attention. :)

However, I can get the node to go dark grey with 3 inputs (for some reason my version does not have font color set to null), but if I feed "bad" data into one of the other inputs, the node stops working without a warning message.

![image](https://cloud.githubusercontent.com/assets/16838885/12523163/f1969d32-c122-11e5-9c81-59490dfa7fea.png)

Now, I know I am nit-picking. I do not really want you to go back and put warning messages for every idiotic thing i might do. I am sure you have much more important things to work on. I am just checking to see if you knew this.

tim

**Comment by ksobon** [comment]
Now second part of the question about the Format Excel node. Trick is that I have implemented "live formatting" into this node. This means that you no longer have to close Excel to use it In case that you do not supply File Path it will check if Excel is open, and use the active Worksheet in currently open Excel file. Just keep in mind to keep one Excel file open at a time or it could get a little confusing. :-) Here's a demo: 

![image](https://cloud.githubusercontent.com/assets/529781/12524186/560b90be-c129-11e5-83c7-0096ac4e79e2.png)

Notice how leaving inputs out for Graphic Style only sets Fill Style while not making any changes to Text and Border Style. Also, you don't have to supply SheetName when working in "live" mode. 

Another option is the typical mode when Excel is saved on a drive and you cannot have it open. 

![image](https://cloud.githubusercontent.com/assets/529781/12524338/595b2a94-c12a-11e5-8adb-4b134efaf831.png)

Notice that in this case you need a SheetName and FilePath inputs. 

Also, Dynamo nodes should be pretty good about returning errors about wrong type of data provided. For example: Color input as a String should result with: 

![image](https://cloud.githubusercontent.com/assets/529781/12524392/b9d7472c-c12a-11e5-838c-1d04c149b922.png)

This message is pretty clear. It always means that one of the inputs is not of the correct type. 

This is correct: 

![image](https://cloud.githubusercontent.com/assets/529781/12524420/e721cd88-c12a-11e5-81c5-6ffeaaa80339.png)

OK, I did notice a thing or two missing when I was responding so I will re-post updated Bumblebee today. It will have some input types specified better so that you get better warnings. They were previously all set to a generic "var" instead of "int", "Color", "bool" etc hence the missing errors. 

Thanks for reporting.

**Comment by teghill** [comment]
Thank you for fixing.

Also thank you for the hover on input, that is really useful to know.

You should really write an idiots guide to Dynamo.

**Comment by ksobon** [comment]
Tim, 

You are definitely not an idiot. Bumblebee has its quirks and stuff that is still missing. I am not exactly working on this all the time, so I need input from people like you to catch them all. 

I am working on one more feature that was requested here that will allow reading excel files by named ranges. When I am done, i will post new Bumblebee. 

Also, those hover over inputs only work for select few types of data. I think Dynamo team is working on this to add more, but unless its a string, int or a bool I can't add a hover over. It doesn't work for custom classes like BBData or BBStyle.
